steps:
  # Build TRAIN image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build train image'
    args: [
      'build',
      '.',  # build context is repo root (we'll submit from there)
      '-t',
      'europe-west1-docker.pkg.dev/$PROJECT_ID/repo1/train:latest',
      '-f',
      'dockerfiles/train.dockerfile'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push train image'
    args: [
      'push',
      'europe-west1-docker.pkg.dev/$PROJECT_ID/repo1/train:latest'
    ]



options:
  logging: CLOUD_LOGGING_ONLY
